// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPeysrOD3afRckdV1ixMTpHJ7YieVgY-I',
    appId: '1:1072707207855:web:3b8977c88857b4503eca5a',
    messagingSenderId: '1072707207855',
    projectId: 'future-pathai',
    authDomain: 'future-pathai.firebaseapp.com',
    storageBucket: 'future-pathai.firebasestorage.app',
    measurementId: 'G-4F34EH7J18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs3YBkZdsyy2lIL5Md2_0GPqwc1_T5hVA',
    appId: '1:1072707207855:android:b28eeae5698cc8e83eca5a',
    messagingSenderId: '1072707207855',
    projectId: 'future-pathai',
    storageBucket: 'future-pathai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9aps4RLffb_Vxx_-DyCen3WvCD2bEmtc',
    appId: '1:1072707207855:ios:0bf333e7ea6f510f3eca5a',
    messagingSenderId: '1072707207855',
    projectId: 'future-pathai',
    storageBucket: 'future-pathai.firebasestorage.app',
    iosClientId: '1072707207855-74dafffc7dqgqlhi33liipcrcklhbag3.apps.googleusercontent.com',
    iosBundleId: 'com.futurepathai.futurepathai',
  );
}
